apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors-rabbit
  labels:
    app.kubernetes.io/part-of: spring-sensors-rabbit
    apps.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://github.com/pvdbleek/spring-sensors-rabbit.git
      ref:
        branch: main
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rmq-1

